project:
  type: website

website:
  title: "California Housing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Ocean_Proximity.qmd
        text: Ocean Proximity
      - href: Map.qmd
        text: Map
      - href: model.qmd
        text: Model
      - href: Sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



